### PR TITLE
Validate frames

### PR DESCRIPTION
**Pull request by doudou**

### CODE REVIEW

**Comment by doudou** [comment]
Ping @gustavoneves12

**Comment by doudou** [comment]
And re-ping

**Comment by doudou** [comment]
Pingoooooo @gustavoneves12

**Comment by doudou** [comment]
Ping ping ping ping @gustavoneves12

**Comment by gustavoneves12** [comment]
I am going to review this.

**Comment by gustavoneves12** [comment]
I am going to review this!

**Pull request merged**
