### PR TITLE
Laser line integration

### PR DESCRIPTION
**Pull request by gustavoneves12**
create properties to config laser line.
create dynamic ports to receive laser scan data.
create vizkit3d laser line plugin and add it in the vizkit3d world.

### CODE REVIEW

**Comment by doudou** [comment]
Since this is flat_fish_camera_simulation, there's really no need to use dynamic ports (which are pretty complicated ...). Just define as many ports as required by flat fish.

**Comment by gustavoneves12** [comment]
@doudou (PING)

**Comment by doudou** [comment]
You did not see my comment above ...

**Comment by gustavoneves12** [comment]
So, do I need to change the dynamic ports and create 2 static ports to receive laser line data?

**Comment by doudou** [comment]
Yes. That will simplify the implementation _a lot_. The whole point of flat_fish_camera_simulation is that it is flatfish specific.

**Comment by gustavoneves12** [comment]
@doudou (PING)

**Comment by doudou** [comment]
This will have to wait for https://github.com/Brazilian-Institute-of-Robotics/gui-vizkit3d_laser_line/pull/2 to be merged

**Pull request merged**
